// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzklyLEE-BDSNnv8PFjbAKG3tQjUVsy5Y',
    appId: '1:1063679269012:web:3d4f049b690c0ef86efc81',
    messagingSenderId: '1063679269012',
    projectId: 'buspay-48487',
    authDomain: 'buspay-48487.firebaseapp.com',
    storageBucket: 'buspay-48487.firebasestorage.app',
    measurementId: 'G-6VZ46CB3V4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDAcTa2Zehvc22aWIrXipK_ToXZAosvk4',
    appId: '1:1063679269012:android:89069c78cebb259d6efc81',
    messagingSenderId: '1063679269012',
    projectId: 'buspay-48487',
    storageBucket: 'buspay-48487.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_T7-ePYcSvC9G-Z947UtKAf15PiR3HkU',
    appId: '1:1063679269012:ios:f825a366f82a9d986efc81',
    messagingSenderId: '1063679269012',
    projectId: 'buspay-48487',
    storageBucket: 'buspay-48487.firebasestorage.app',
    iosBundleId: 'com.example.flutterCourses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_T7-ePYcSvC9G-Z947UtKAf15PiR3HkU',
    appId: '1:1063679269012:ios:f825a366f82a9d986efc81',
    messagingSenderId: '1063679269012',
    projectId: 'buspay-48487',
    storageBucket: 'buspay-48487.firebasestorage.app',
    iosBundleId: 'com.example.flutterCourses',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzklyLEE-BDSNnv8PFjbAKG3tQjUVsy5Y',
    appId: '1:1063679269012:web:da7a766541ac77ae6efc81',
    messagingSenderId: '1063679269012',
    projectId: 'buspay-48487',
    authDomain: 'buspay-48487.firebaseapp.com',
    storageBucket: 'buspay-48487.firebasestorage.app',
    measurementId: 'G-LKDYN4CFHB',
  );

}